---
title: "Your Document Title"
author: "Document Author"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

# Covid-19 by 
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(selectr)
library(xml2)
library(XML)
library(janitor)
library(data.table)
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(plotly)
library(forcats)

abbr <- strsplit("AL – Alabama
AK – Alaska
AZ – Arizona
AR – Arkansas
CA – California
CO – Colorado
CT – Connecticut
DE – Delaware
FL – Florida
GA – Georgia
HI – Hawaii
ID – Idaho
IL – Illinois
IN – Indiana
IA – Iowa
KS – Kansas
KY – Kentucky
LA – Louisiana
ME – Maine
MD – Maryland
MA – Massachusetts
MI – Michigan
MN – Minnesota
MS – Mississippi
MO – Missouri
MT – Montana
NE – Nebraska
NV – Nevada
NH – New Hampshire
NJ – New Jersey
NM – New Mexico
NY – New York
NC – North Carolina
ND – North Dakota
OH – Ohio
OK – Oklahoma
OR – Oregon
PA – Pennsylvania
RI – Rhode Island
SC – South Carolina
SD – South Dakota
TN – Tennessee
TX – Texas
UT – Utah
VT – Vermont
VA – Virginia
WA – Washington
WV – West Virginia
WI – Wisconsin
WY – Wyoming", "\\n") %>%
  unlist()
```

## Your Familiar Tools

Feel free to use the `knitr` infrastructure with dozens of tunable options in
your document.

```{r fig.width=6, fig.height=6, fig.align='center'}
url <- "https://simple.wikipedia.org/wiki/List_of_United_States_governors"
political_party <- read_html(url) %>%
  html_node("table") %>%
  html_table(header = T) %>%
  row_to_names(1) %>%
  select(!c(2,4,10,11))
```

```{r}
abbr <- tibble(data = abbr) %>%
  separate(data, into = c("Abbr", "State"), sep = " – ")

```

```{r}
covid <- fread("United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv") %>%
  filter(state %in% abbr$Abbr) %>%
  group_by(state) %>%
  filter(submission_date == max(submission_date))

```

```{r}
census <- read.csv("csvData.csv") %>%
  select(!`ï..rank`)

```


```{r}
covid_PP <- covid %>%
  inner_join(abbr, by = c("state" = "Abbr")) %>%
  inner_join(political_party, by = "State") %>%
  inner_join(census, by = "State") %>%
  mutate(perc_cases = tot_cases/Pop2018 * 100,
         perc_death_by_cases = tot_death/tot_cases * 100,
         perc_death_by_pop = tot_death/Pop2018 * 100,
         Party = str_extract(Party, "Republican|Democratic")) %>%
  select(State, Party, perc_death_by_pop, perc_death_by_cases, perc_cases, tot_cases, tot_death)
  
  
ggplot(covid_PP, aes(x = Party, y = perc_cases, fill = Party)) +
  geom_boxplot(fill = c("Blue", "Red"))
```




```{r}
lm(covid_PP$perc_cases ~ covid_PP$Party, alternative = "two.sided", paired = F, var.equal = FALSE) %>%
  summary()
```

```{r}
plot_geo(covid_PP, locationmode = 'USA-states') %>%
  add_trace(
    z = ~perc_cases, locations = ~state,
    color = ~perc_cases, colors = "Blues"
  ) %>%
  layout(
    title = "Percent Infected by State",
    geo = 
      list(
      scope = 'usa',
      projection = list(type = 'albers usa')
      )
  ) %>%
  colorbar(title = "Percent Infected")
```


```{r}
ggplot(covid_PP, aes(fct_reorder(State, perc_cases), perc_cases, color = Party)) +
  geom_point() +
  geom_hline(yintercept = mean(covid_PP$perc_cases), linetype = "dashed") +
  scale_colour_manual(values = c("Blue", "Red")) +
  labs(x = "State", y = "Percent of Population Infected") +
  coord_flip() +
  theme_minimal()

```
